name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
env:
    HAKAI_API_CREDENTIALS: ${{ secrets.HAKAI_API_CREDENTIALS }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install .
      - run: python hakai_ctd_issues
      - run: mkdocs gh-deploy --force